version: '3.7'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    links:
      - db
    environment:
      - DB_USERNAME
      - DB_PASSWORD
  db:
    build: ./docker/db
    expose:
      - '5432'
    environment:
      - POSTGRES_PASSWORD
      - DB_USERNAME
      - DB_PASSWORD
    volumes:
      - ./docker/initdb:/docker-entrypoint-initdb.d/
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local
